# Generated by Django 4.1.6 on 2023-11-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, null=True)),
                ('mean', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
