# Generated by Django 4.1.6 on 2023-11-22 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0002_fail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fail',
        ),
    ]
